replicas: 3
service:
  name: http
  port: 80
application:
  name: backend-app
  namespace: backend
  version: v1.0.0
  image: docker.io/mccutchen/go-httpbin
  tag: v2.15.0
  imagePullPolicy: IfNotPresent
  port: 8080
  

