apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.name }}
  labels:
    app: {{ .Values.application.name }}
    service: {{ .Values.application.name }}
spec:
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.application.port }}
  selector:
    app: {{ .Values.application.name }}